### PR TITLE
str.format(**dict)

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by wgaylord** [comment]
I need to push what I have. (I did alotnof rewriting. To make it also work with MCP mappings.)

**Comment by cclauss** [comment]
I will close this pull request and I can resurrect it once you have pushed your changes.

**Comment by wgaylord** [comment]
I will manually add it in before I push if that is fine?

**Comment by cclauss** [comment]
That works.  Go for it.

**Pull request closed without merging**
